name: Batch

on:
  push:
    branches:
      - main
  schedule:
  - cron: '50 12 * * *'
  workflow_dispatch:

jobs:
  batch-deposit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: yarn install
      run: yarn && cd packages/cli && yarn
    - name: yarn run batch-deposit
      env:
        ROLLUP_SCRIPT_ARGS: "0x86c7429247beba7ddd6e4361bcdfc0510b0b644131e2afb7e486375249a01802"
        GODWOKEN_WEB3_URL: "https://godwoken-betanet-v1.ckbapp.dev"
        CKB_RPC_URL: "https://testnet.ckb.dev"
        CKB_INDEXER_URL: "https://testnet.ckb.dev/indexer"
      working-directory: packages/cli
      run: |
        yarn run batch-deposit \
          --lumos-config BETANET \
          --private-key ${{ secrets.GODWOKEN_BENCHMARK_PRIVKEY }} \
          --capacity 5001000000000 \
          --n-derived-accounts 11

  batch-withdraw:
    needs: [ batch-deposit ]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: yarn install
      run: yarn && cd packages/cli && yarn
    - name: yarn run batch-withdraw
      env:
        ROLLUP_SCRIPT_ARGS: "0x86c7429247beba7ddd6e4361bcdfc0510b0b644131e2afb7e486375249a01802"
        GODWOKEN_WEB3_URL: "https://godwoken-betanet-v1.ckbapp.dev"
        CKB_RPC_URL: "https://testnet.ckb.dev"
        CKB_INDEXER_URL: "https://testnet.ckb.dev/indexer"
      working-directory: packages/cli
      run: |
        yarn run batch-withdraw \
          --lumos-config BETANET \
          --private-key ${{ secrets.GODWOKEN_BENCHMARK_PRIVKEY }} \
          --fee 100 \
          --n-derived-accounts 11
